# Generated by Django 4.2.9 on 2024-01-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0003_remove_replycomplaint_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer',
        ),
    ]
