# Generated by Django 4.2.9 on 2024-01-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0004_remove_complaint_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomplaint',
            old_name='Complaint',
            new_name='original_complaint',
        ),
    ]
