# Generated by Django 4.2.9 on 2024-01-26 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0006_paymentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCollectedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_collection_area', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.garbagecollector')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.driver')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garbagereport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
